replicaCount: 2

imageName: lemonpro/maddadjokes
imageTag: beta
imagePullPolicy: Always

containerPort: 8080

contextPath: "/maddadjokes"

ingress:
  host: ejbtechsolutions.com
  wwwhost: www.ejbtechsolutions.com
  tls:
    - hosts:
        - ejbtechsolutions.com
        - www.ejbtechsolutions.com
      secretName: ejbtechsolutions-com

configs:
  GIN_MODE: release

resources:
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

startupFailureThreshold: 10
livenessFailureThreshold: 10
readinessFailureThreshold: 10
